baseURL = 'https://koji223.github.io/'
languageCode = 'en-us'
title = 'Koji Tsutsumi Lab'
theme = 'PaperMod'

[pagination]
  pagerSize = 10

[params]
  defaultTheme = 'auto'
  ShowBreadCrumbs = true

[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url  = "/publications/"
  weight = 2
